name: Build and deploy site to Deta
on:
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site
        run: mkdocs build --clean

      - name: Build featured.md
        run: |
          [ -f feature.json ] || echo "json file not found!"
          [ -f feature.py ] || echo "py file not found!"
          [ -f docs/featured.md ] || echo "md file not found!"
          python feature.py

      - name: Deploy to Deta
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'basic-deta'
          deta-project: 'fastapi'
          deta-project-dir: '.'
